"""Reliability reason codes."""

from __future__ import annotations

STALE_PROCEDURE = "STALE_PROCEDURE"
SINGLE_SOURCE_SUPPORT = "SINGLE_SOURCE_SUPPORT"
HIGH_AUTHORITY_CONFLICT = "HIGH_AUTHORITY_CONFLICT"
ACTION_NOT_AUTHORIZED = "ACTION_NOT_AUTHORIZED"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
QUARANTINED_MEMORY = "QUARANTINED_MEMORY"
SUPERSEDED_MEMORY = "SUPERSEDED_MEMORY"
LOW_MEMORY_CONFIDENCE = "LOW_MEMORY_CONFIDENCE"
ACTIVE_MIGRATION = "ACTIVE_MIGRATION"
INFERRED_ONLY = "INFERRED_ONLY"
